Repository jbake-org/jbake, pull requests merged in 2018-04, with the labels that each got.

#438 reduce distribution size
  build.gradle
  jbake-core/build.gradle
  jbake-core/src/test/java/org/jbake/FakeDocumentBuilder.java
Labels: enhancement

#432 Updated developers list
  gradle/maven-publishing.gradle
Labels: task

#442 Fixes #441
  jbake-core/src/main/java/org/jbake/parser/MarkupEngine.java
Labels: bugfix

#444 Fix for #439
  jbake-core/src/main/resources/default.properties
Labels: bugfix

#446 align build doc with current setup
  BUILD.adoc
Labels: documentation

#447 adjust jvmargs. fix compile warnings.
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#449 Manually merged in #430
  .travis.yml
  build.gradle
  gradle/sonarqube.gradle
  jbake-core/build.gradle
  jbake-core/src/main/java/org/jbake/app/Crawler.java
  jbake-core/src/main/java/org/jbake/app/DocumentList.java
  jbake-core/src/main/java/org/jbake/app/Parser.java
  jbake-core/src/main/java/org/jbake/app/Renderer.java
  jbake-core/src/main/java/org/jbake/model/DocumentTypeUtils.java
  jbake-core/src/main/java/org/jbake/model/DocumentTypes.java
  jbake-core/src/main/java/org/jbake/render/IndexRenderer.java
  jbake-core/src/main/java/org/jbake/template/ModelExtractor.java
  jbake-core/src/main/java/org/jbake/template/model/TagsExtractor.java
  jbake-core/src/main/java/org/jbake/util/PagingHelper.java
  jbake-core/src/test/java/org/jbake/util/PagingHelperTest.java
Labels: task

#454 Closes #453 - SDKMAN Gradle plugin
  gradle/sdkman.gradle
Labels: change

#457 update gradle to 4.7. jdk10 support. ci log mode.
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: change

#452 Prepare for next version 2.7.0
  gradle.properties
Labels: change, task

#458 Fixes #456
  jbake-core/src/main/java/org/jbake/app/FileUtil.java
  jbake-core/src/main/java/org/jbake/app/ZipUtil.java
Labels: bugfix
