Repository jbake-org/jbake, pull requests merged in 2018-11, with the labels that each got.

#561 Moved DebugUtil class to util package
  jbake-core/src/main/java/org/jbake/util/DebugUtil.java
  jbake-core/src/test/java/org/jbake/app/DebugUtilTest.java
Labels: change

#564 Add current dir lib/* and lib/logging to classpath
  gradle/application.gradle
Labels: enhancement

#568 Catch all classloading issues
  jbake-core/src/main/java/org/jbake/template/TemplateEngines.java
Labels: bugfix
