Repository jbake-org/jbake, pull requests merged in 2019-01, with the labels that each got.

#574 add checkstyle rules
  BUILD.adoc
  README.asciidoc
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: enhancement

#588 update dependencies compatible with jdk 7
  build.gradle
  jbake-core/src/main/java/org/jbake/parser/MarkdownEngine.java
  jbake-core/src/test/java/org/jbake/launcher/MainTest.java
  jbake-dist/build.gradle
Labels: change

#590 Release v2.6.4
  gradle.properties
Labels: task
