Repository jbake-org/jbake, pull requests merged in 2021-02, with the labels that each got.

#648 Don't assume document types are valid identifiers in OrientDB
  jbake-core/src/main/java/org/jbake/app/ContentStore.java
  jbake-core/src/test/java/org/jbake/app/ContentStoreTest.java
Labels: affects:v2.6.5, bugfix

#654 use svg for gitter shield
  README.asciidoc
Labels: documentation

#660 Updated links for Travis
  README.asciidoc
Labels: change

#661 Removed line from readme.
  README.asciidoc
Labels: change, documentation
