Repository jbake-org/jbake, pull requests merged in 2021-05, with the labels that each got.

#687 add index.html to the list of known welcome files for jetty
  jbake-core/src/main/java/org/jbake/launcher/JettyServer.java
Labels: bugfix

#682 Use lower log level to report missing template engine
  jbake-core/src/main/java/org/jbake/template/TemplateEngines.java
Labels: change

#646 Wrap usage at 80 characters instead of 100
  jbake-core/src/main/java/org/jbake/launcher/Main.java
Labels: change

#653 jbake issue #652: prev/next post navigation only uses published posts
  jbake-core/src/main/java/org/jbake/render/DocumentsRenderer.java
  jbake-core/src/test/java/org/jbake/render/DocumentsRendererTest.java
Labels: bugfix

#676 (feat) Output abbreviated git hash during CLI execution #675
  jbake-core/build.gradle
  jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java
  jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java
  jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java
  jbake-core/src/main/java/org/jbake/launcher/Main.java
  jbake-core/src/main/resources/default.properties
Labels: change

#589 enabled checkstyle rule allowSingleLineStatement
  config/checkstyle/checkstyle.xml
  jbake-core/src/main/java/org/jbake/app/ContentStore.java
  jbake-core/src/main/java/org/jbake/template/DelegatingTemplateEngine.java
  jbake-core/src/main/java/org/jbake/util/PagingHelper.java
  jbake-core/src/test/java/org/jbake/app/ContentStoreIntegrationTest.java
  jbake-core/src/test/java/org/jbake/app/DebugUtilTest.java
  jbake-core/src/test/java/org/jbake/app/MdParserTest.java
  jbake-core/src/test/java/org/jbake/launcher/MainTest.java
  jbake-core/src/test/java/org/jbake/render/support/MockCompositeConfiguration.java
  jbake-dist/src/smoke-test/java/org/jbake/BuiltInProjectsTest.java
  jbake-dist/src/smoke-test/java/org/jbake/ProjectWebsiteTest.java
Labels: enhancement

#639 feat: Allow the file used to ignore directories to be specified
  jbake-core/src/main/java/org/jbake/app/Asset.java
  jbake-core/src/main/java/org/jbake/app/Crawler.java
  jbake-core/src/main/java/org/jbake/app/FileUtil.java
  jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java
  jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java
  jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java
  jbake-core/src/main/resources/default.properties
  jbake-core/src/test/java/org/jbake/app/AssetTest.java
  jbake-core/src/test/java/org/jbake/app/FileUtilTest.java
  jbake-core/src/test/java/org/jbake/app/configuration/ConfigUtilTest.java
  jbake-core/src/test/resources/fixture/assets/fooignorablefolder/.fooignore
  jbake-core/src/test/resources/fixture/assets/fooignorablefolder/file_in_foo_ignored_folder.html
  jbake-core/src/test/resources/fixture/assets/ignorablefolder/.jbakeignore
  jbake-core/src/test/resources/fixture/assets/ignorablefolder/file_in_ignored_folder.html
Labels: enhancement

#684 Add support for data files specifically in YAML format
  gradle.properties
  jbake-core/build.gradle
  jbake-core/src/main/java/org/jbake/app/Crawler.java
  jbake-core/src/main/java/org/jbake/app/FileUtil.java
  jbake-core/src/main/java/org/jbake/app/Oven.java
  jbake-core/src/main/java/org/jbake/app/configuration/DefaultJBakeConfiguration.java
  jbake-core/src/main/java/org/jbake/app/configuration/JBakeConfiguration.java
  jbake-core/src/main/java/org/jbake/app/configuration/JBakeProperty.java
  jbake-core/src/main/java/org/jbake/launcher/BakeWatcher.java
  jbake-core/src/main/java/org/jbake/parser/YamlEngine.java
  jbake-core/src/main/java/org/jbake/template/FreemarkerTemplateEngine.java
  jbake-core/src/main/java/org/jbake/template/model/AllContentExtractor.java
  jbake-core/src/main/java/org/jbake/template/model/DataExtractor.java
  jbake-core/src/main/java/org/jbake/util/DataFileUtil.java
  jbake-core/src/main/resources/META-INF/org.jbake.parser.MarkupEngines.properties
  jbake-core/src/main/resources/META-INF/org.jbake.template.ModelExtractors.properties
  jbake-core/src/main/resources/default.properties
  jbake-core/src/test/java/org/jbake/app/CrawlerTest.java
  jbake-core/src/test/java/org/jbake/template/ModelExtractorsTest.java
  jbake-core/src/test/resources/fixture/data/videos.yaml
Labels: enhancement
