Repository jbake-org/jbake, pull requests merged in 2022-03, with the labels that each got.

#736 Fix for data files being referenced from Pebble templates
  jbake-core/src/main/java/org/jbake/template/model/DataExtractor.java
Labels: bugfix

#744 Use blocking method rather than the throwing one
  jbake-maven-plugin/src/main/java/org/jbake/maven/util/DirWatcher.java
Labels: bugfix, maven-plugin

#758 As adoptopenjdk is deprecated the dependencies should be adopted to its successor adoptium/temurin
  Dockerfile
Labels: change

#756 Change DuplicatesStrategy from EXCLUDE to INCLUDE
  jbake-core/build.gradle
Labels: bugfix
